services:
  db:
    image: mysql:9.1
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
     # MYSQL_USER: root
     # MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: erudiodb
    ports:
      - "3308:3306"
    networks:
      - avila-network

  avila-api-rest:
    build: ./rest-spring-boot
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/erudiodb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
    command: mvn spring-boot:run
    depends_on:
      - db
    ports:
      - "127.0.0.1:80:80"
    networks:
      - avila-network

networks:
  avila-network:
