name: Continuos Integration an Delivery GH

on:
  push:
    branches:
      - "main"
      - "master"


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Application .jar
        working-directory: ./rest-spring-boot
        run: mvn clean package

      - name: Docker compose build
        working-directory: ./SpringBoot
        run: docker compose build

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag rest-spring-boot-avila-api-rest:latest ${{ secrets.DOCKER_USERNAME }}/rest-spring-boot-avila-api-rest::${{ github.run_id }}
          
          docker push ${{ secrets.DOCKER_USERNAME }}/rest-spring-boot-avila-api-rest:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rest-spring-boot-avila-api-rest:${{ github.run_id }}
          
        






